### ISSUE TITLE
Demo of MapBuilder

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-mapbuilder-module#4]
I think the readme should have a demo URL.

I have noticed it's not on : https://demo.lizmap.com/lizmap/
but it's only on : https://demo.lizmap.com/lizmap_3_2/

**Comment by nboisteault** [comment]
Good idea ! Fixed with https://github.com/3liz/lizmap-mapbuilder-module/commit/92e34a8ce3614f52f658ec6f580b76b4cb95de49

**Comment by Gustry** [comment]
@nboisteault Is-it not another bug that it's not on https://demo.lizmap.com/lizmap/ ? I don't know where to raise this issue.

**Comment by nboisteault** [comment]
@Gustry I reopen issue and ask here.
@laurentj could you add mapbuilder to https://demo.lizmap.com/lizmap/ ?

**Comment by laurentj** [comment]
@nboisteault no. we should create a specific instance for each specific modules. Because:

- I don't want the official demo to become a christmas tree ;-)
- people may think that features provided by a specific module are standard feature of Lizmap.

You should create a specific ticket on our gitlab ;-) Github should not be used for our internal needs...

**Comment by Gustry** [comment]
Ticket created ;-)
